import os
import logging

from models import RedditThreadCollection
from constants import LLMConstants

logging.basicConfig(
    format="%(asctime)s.%(msecs)03d - %(name)s:%(levelname)s - pid %(process)d - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    level=logging.INFO,
)

logger = logging.getLogger(__name__)


def main(input_directory, output_directory):
    logger.info("Publishing summary as string")
    collection = RedditThreadCollection.from_json_file(
        os.path.join(input_directory, "summarised_threads.json")
    )
    string = f"Reddit Roundup, generated by {LLMConstants.model}\n"
    string += "\nTLDR:\n"
    string += f"{collection.summary}\n\n"
    for i, thread in enumerate(collection.threads):
        string += (
            f"Thread Summary {i + 1}: "
            f"https://www.reddit.com{thread.submission.permalink}\n"
            f"{thread.submission.date}\n"
        )
        string += f"{thread.summary}\n\n"
    with open(os.path.join(output_directory, "summary.txt"), "w") as file:
        file.write(string)
