import os
import logging
from utils.reddit import RedditThreadCollection
from constants import LLMConstants


# Temporary function to format the final summary string
# This will be replaced by a workflow template in produciton
# That sends the summary directly to Slack.

logging.basicConfig(
    format="%(asctime)s.%(msecs)03d - %(name)s:%(levelname)s - pid %(process)d - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    level=logging.INFO,
)

logger = logging.getLogger(__name__)

def main(input_directory, output_directory):

    logger.info("Publishing to summary as string")
    collection = RedditThreadCollection.from_json(
        os.path.join(input_directory, "summarised_threads.json")
    )
    string = (
        f":roo::robot_face: Reddit Roundup, generated by {LLMConstants.model} :robot_face::roo:\n"
    )
    string += "\nTLDR:\n"
    string += f"{collection.summary}\n\n"
    for i, thread in enumerate(collection.threads):
        string += f"Thread Summary {i+1}: https://www.reddit.com{thread.submission.permalink}\n{thread.submission.date}\n"
        string += f"{thread.summary}\n\n"
    with open(os.path.join(output_directory, "slack_message.txt"), "w") as file:
        file.write(string)
